[default]
src = 'src'
out = 'out'
libs = ['lib']
fuzz_runs = 256
optimizer = true
optimizer_runs = 200
remappings = [
  'ds-test/=lib/ds-test/src/',
  'forge-std/=lib/forge-std/src/',
  '@yearnvaults/=lib/yearn-vaults/',
  '@openzeppelin/=lib/openzeppelin-contracts/',
]
verbosity = 3
